# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!
#source 'https://github.com/CocoaPods/Specs.git'
# 请不要遗漏Master仓库。
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/aliyun/aliyun-specs.git'
target 'DDAdvHeader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.0.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
